import { AdminRoles } from "@prisma/client";

const { ADMINISTRATOR, MODERATOR, MEMBER } = AdminRoles;

//permission keys
export const Permission = {
    // Verification queue
    VERIFICATION_VIEW: "VERIFICATION_VIEW",
    STUDENT_VERIFY: "STUDENT_VERIFY",
    STUDENT_DELETE: "STUDENT_DELETE",

    // Masterlist
    MASTERLIST_VIEW: "MASTERLIST_VIEW",
    MASTERLIST_EXPORT: "MASTERLIST_EXPORT",
    STUDENT_PASSWORD_RESET: "STUDENT_PASSWORD_RESET",

    // Finalization
    FINALIZE_VIEW: "FINALIZE_VIEW",
    FINALIZE_UPDATE: "FINALIZE_UPDATE",
    FINALIZE_STATUS: "FINALIZE_STATUS",

    // Attendance
    ATTENDANCE_VIEW: "ATTENDANCE_VIEW",
    ATTENDANCE_OVERRIDE: "ATTENDANCE_OVERRIDE",

    // Booking
    BOOKING_VIEW: "BOOKING_VIEW",
    BOOKING_CREATE: "BOOKING_CREATE",
    BOOKING_TOGGLE: "BOOKING_TOGGLE",
    BOOKING_UPDATE: "BOOKING_UPDATE",

    // Staff management
    STAFF_VIEW: "STAFF_VIEW",
    STAFF_MANAGE_ROLE: "STAFF_MANAGE_ROLE",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

//who can do what
export const PERMISSION_MATRIX: Record<Permission, AdminRoles[]> = {
    [Permission.VERIFICATION_VIEW]: [ADMINISTRATOR, MODERATOR],
    [Permission.STUDENT_VERIFY]: [ADMINISTRATOR, MODERATOR],
    [Permission.STUDENT_DELETE]: [ADMINISTRATOR],

    [Permission.MASTERLIST_VIEW]: [ADMINISTRATOR, MODERATOR, MEMBER],
    [Permission.MASTERLIST_EXPORT]: [ADMINISTRATOR, MODERATOR],
    [Permission.STUDENT_PASSWORD_RESET]: [ADMINISTRATOR, MODERATOR],

    [Permission.FINALIZE_VIEW]: [ADMINISTRATOR, MODERATOR],
    [Permission.FINALIZE_UPDATE]: [ADMINISTRATOR, MODERATOR],
    [Permission.FINALIZE_STATUS]: [ADMINISTRATOR, MODERATOR],

    [Permission.ATTENDANCE_VIEW]: [ADMINISTRATOR, MODERATOR],
    [Permission.ATTENDANCE_OVERRIDE]: [ADMINISTRATOR, MODERATOR],

    [Permission.BOOKING_VIEW]: [ADMINISTRATOR, MODERATOR],
    [Permission.BOOKING_CREATE]: [ADMINISTRATOR],
    [Permission.BOOKING_TOGGLE]: [ADMINISTRATOR],
    [Permission.BOOKING_UPDATE]: [ADMINISTRATOR],

    [Permission.STAFF_VIEW]: [ADMINISTRATOR],
    [Permission.STAFF_MANAGE_ROLE]: [ADMINISTRATOR],
};
